#!/usr/bin/env bash
# setting up Nginx on a remote server with a bash script

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > sudo tee /var/www/html/index.html;
service nginx start
