#!/usr/bin/env bash
# setting up Nginx on a remote server with a bash script

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start
