#!/usr/bin/env bash
# Installs, configures, and starts the server
sudo apt-get -y update
sudo apt-get -y install nginx

# Creating an index.html page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
redirlink="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com/Torh-21 permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

# Restart Nginx after implementing changes
sudo service nginx restart
