#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
str_for_redir="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Torh-21 permanent;"

sed -i "s/server_name _;/$str_for_redir/" /etc/nginx/sites-enabled/default

# Testing configurations syntax errors
sudo nginx -t

# Restart Nginx after implementing changes
sudo service nginx restart
