#!/usr/bin/env bash
#configure a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
str_for_redir="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Torh-21 permanent;"

sudo sed -i "s/server_name _;/$str_for_redir/" /etc/nginx/sites-enabled/default

# Creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

str_for_err="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\t\internal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$str_for_err/" /etc/nginx/sites-enabled/default

# Testing configurations syntax errors
sudo nginx -t

# Restart Nginx after implementing changes
sudo service nginx restart
