#!/bin/bash
# This bash script configures Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

# Creating an index.html page
echo 'Hello World' | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

server_comms=\
"server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   location /redirect_me {
      return 301 https://www.github.com/Torh-21;
   }

   error_page 404 /404.html;
   location = /404.html{
      internal;
   }

   add_header X-Served-By $hostname;
}"

echo "$server_comms" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
