#!/bin/bash
# This bash script configures Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

# Creating an index.html page
echo 'Hello World' | sudo tee /var/www/html/index.html

# Creating a Permanent redirect link (301)
redir_var="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Torh-21 permanent;"

sudo sed -i "s/server_name _;/$redir_var/" /etc/nginx/sites-enabled/default

# Creating the error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

str_for_err="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\t\internal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$str_for_err/" /etc/nginx/sites-enabled/default

# Setting up the custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Checking for configuration syntax errors
sudo nginx -t

# Restart Nginx after making changes
sudo service nginx restart
