#!/bin/bash
# This bash script configures Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
# Creating an index.html page
echo 'Hello World' > /var/www/html/index.html

# Creating the error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.github.com/Torh-21 permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

echo "$server_config" > /etc/nginx/sites-enabled/default

# Checking for configuration syntax errors
sudo nginx -t

# Restart Nginx after making changes
sudo service nginx restart
