#!/usr/bin/env bash
# This bash script listens on port 80 for all active servers
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
