#!/usr/bin/env bash
# A script that stops 4-to_infinity_and_beyond process.

# Find the process ID (PID) of 4-to_infinity_and_beyond
PID=$(pgrep -a "bash" | grep "4-to_infinity" | cut -d' ' -f1)

# Stop the process with the given PID
kill $PID
