#!/usr/bin/env bash
# This bash script configures the container so nginx is running as nginx user
pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
